[package]
name = "ronnie-crypto"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
openssl = "0.10.57"
thiserror = "1.0.49"

[dev-dependencies]
hex = "0.4.3"

